<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="admin.aspx.vb" Inherits="WebAnatartica.admin" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
>

<html lang="en">
<head runat="server">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admin - Antartica Animals</title>
     <script  type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script  type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css"/>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/Styles/Site.css" rel="stylesheet" type="text/css" />

    <webopt:BundleReference runat="server" Path="~/Content/css" />
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    
</head>
<body>
    <form runat="server">
        <asp:ScriptManager runat="server">
            <Scripts>


                <asp:ScriptReference Name="MsAjaxBundle" />
                <%--<asp:ScriptReference Name="jquery" />--%>
                <asp:ScriptReference Name="bootstrap" />
                <asp:ScriptReference Name="WebForms.js" Assembly="System.Web" Path="~/Scripts/WebForms/WebForms.js" />
                <asp:ScriptReference Name="WebUIValidation.js" Assembly="System.Web" Path="~/Scripts/WebForms/WebUIValidation.js" />
                <asp:ScriptReference Name="MenuStandards.js" Assembly="System.Web" Path="~/Scripts/WebForms/MenuStandards.js" />
                <asp:ScriptReference Name="GridView.js" Assembly="System.Web" Path="~/Scripts/WebForms/GridView.js" />
                <asp:ScriptReference Name="DetailsView.js" Assembly="System.Web" Path="~/Scripts/WebForms/DetailsView.js" />
                <asp:ScriptReference Name="TreeView.js" Assembly="System.Web" Path="~/Scripts/WebForms/TreeView.js" />
                <asp:ScriptReference Name="WebParts.js" Assembly="System.Web" Path="~/Scripts/WebForms/WebParts.js" />
                <asp:ScriptReference Name="Focus.js" Assembly="System.Web" Path="~/Scripts/WebForms/Focus.js" />
                <asp:ScriptReference Name="WebFormsBundle" />
            </Scripts>
        </asp:ScriptManager>
        <center>
            <a  href="Default.aspx" class="btn btn-primary"> Home</a>
            <a  href="register.aspx" class="btn btn-primary"> Add New User</a>
            <a  href="login.aspx" class="btn btn-primary"> Logout</a>
            <asp:Label ID="Label1" runat="server" Text="">Total Users :</asp:Label>
          <asp:Label ID="users" runat="server" Text=""></asp:Label>
               
        </center>
        <div class="container">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="false" AutoGenerateEditButton="false">

            </asp:GridView>
        </div>

        <div class="footer">
            <p><strong>Name :</strong> Tomer Kalderon</p>
            <p><strong>Email :</strong> tomerkalderon123@gmail.com</p>
            <p class="copy">All Rights Reserved Copyright "Tomer Kalderon"</p>

        </div>
    </form>
  <script type="text/javascript">
      $(document).ready(function () {
          $('#GridView1').DataTable({
                "paging": true,  // Enable pagination
                "pageLength": 10,  // Set number of rows per page
                "ordering": true  // Enable sorting
            });
      });

      //jQuery(document).ready(function () {
      //    jQuery('#GridView1').DataTable();
      //});
  </script>
</body>
</html>
